Update gpt3_prompts.gs
I have an error coming up on this, which is probably happening on the original now too.
When I fix it, I'll update this and the main branch.

Exception: Request failed for https://api.openai.com returned code 400. Truncated server response: {
  "error": {
    "message": "3 is not valid under any of the given schemas - 'prompt'",
    "type": "invalid_request_error",
    "param": null,
 ... (use muteHttpExceptions option to examine full response)